controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

bundle.security:
    resource: '@BundleSecurityBundle/Resources/config/routes/routes.yaml'
    prefix: /

bundle.setting:
    resource: '@BundleSettingBundle/Resources/config/routes/routes.yaml'
    prefix: /