# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'pt_BR'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Twig\Extension\StringLoaderExtension:

    ######################################################################################################################################################
    # SONATA ADMIN SERVICES
    ######################################################################################################################################################


    ######################################################################################################################################################
    # SECURITY BUNDLE

    settingBundle.setting:
        class: App\Bundle\SettingBundle\Admin\SettingAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Bundle\SettingBundle\Entity\Setting,
                controller: App\Bundle\SettingBundle\Controller\SettingAdminController,
                show_in_dashboard: false,
                on_top: false,
                group: "Setting",
                label: Setting,
                icon: 'fa fa-solid fa-passport',
                setTranslationDomain: '',
            }
            #- { name: sonata.admin, manager_type: orm, group: "Content", label: User, on_top: false, icon: 'fa fa-solid fa-user',, show_in_dashboard: false }

    ######################################################################################################################################################
    # SECURITY BUNDLE

    admin.security.administrator:
        class: App\Bundle\SecurityBundle\Admin\AdministratorAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Bundle\SecurityBundle\Entity\Administrator,
                controller: App\Bundle\SecurityBundle\Controller\AdministratorController,
                show_in_dashboard: true,
                on_top: false,
                group: "Security Admin",
                label: Administrator,
                icon: 'fa fa-solid fa-shield-alt',
            }

    admin.security.group_administrator:
        class: App\Bundle\SecurityBundle\Admin\GroupAdministratorAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Bundle\SecurityBundle\Entity\GroupAdministrator,
                controller: App\Bundle\SecurityBundle\Controller\GroupAdministratorController,
                show_in_dashboard: true,
                on_top: false,
                group: "Security Admin",
                label: Groups,
                icon: 'fa fa-solid fa-shield-alt',
            }

    admin.security.user:
        class: App\Bundle\SecurityBundle\Admin\UserAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Bundle\SecurityBundle\Entity\User,
                controller: App\Bundle\SecurityBundle\Controller\UserController,
                show_in_dashboard: true,
                on_top: false,
                group: "Security Users",
                label: Users,
                icon: 'fa fa-solid fa-users',
            }

    admin.security.group_user:
        class: App\Bundle\SecurityBundle\Admin\GroupUserAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Bundle\SecurityBundle\Entity\GroupUser,
                controller: App\Bundle\SecurityBundle\Controller\GroupUserController,
                show_in_dashboard: true,
                on_top: false,
                group: "Security Users",
                label: Groups,
                icon: 'fa fa-solid fa-users',
            }

    ######################################################################################################################################################
    # MEDIA BUNDLE

    admin.media.media:
        class: App\Bundle\MediaBundle\Admin\MediaAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Bundle\MediaBundle\Entity\Media,
                controller: App\Bundle\MediaBundle\Controller\MediaController,
                show_in_dashboard: true,
                on_top: false,
                group: "Gallery Media",
                label: Media,
                icon: 'fa fa-solid fa-image',
            }